### PR TITLE
Identify agencies

### PR DESCRIPTION
**Pull request by EvilDrPurple**
#### Fixes

* #9 

#### Description

* Attempts to identify agencies from a list of urls
* Optimized the program to trim down a ~1 hour execution time to about ~1 minute for the list of [33000 urls](https://github.com/Police-Data-Accessibility-Project/planning/files/9923552/cd3d48a5-b59c-4de0-a840-3301fb8c8618.csv) which I am pretty happy with. Any other suggestions for further optimization is appreciated
* The logic for matching an agency is shown below:
```mermaid
graph TD;
    A["Find matches of url hostname to agency hostname"]-->|0 matches|B["Return no matches"];
    A-->|1 match|C["Return one match"];
    A-->|2+ matches|D["If url starts with an agency url (same starting path)"];
    D-->|Yes|C
    D-->|No|E["Agency with the most data sources is selected"]
    E-->C
```
* This is by no means perfect but was the best way I could come up with to deal with the case of multiple agencies having the same hostname and get the most accurate results (see Problems)
* When tested using the list of 33000 urls, 47% of links were identified and paired with an agency. 12.6% of links that were successfully identified (6% of total links) used the "most data sources" method (unsure if the agency is correct, but is likely close)

#### Problems

All in all, the identifier accurately identifies the vast majority of links correctly. Some possible reasons for a misidentification are listed below. Some of these can be fixed with updates to the database while others may be unfixable

##### Multiple agencies, same hostname

* Sometimes multiple agencies are on the same hostname. When this is the case it will be assumed that the agency with the most data sources is the correct one. (i.e. Many agencies are located at www1.nyc.gov [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=www1.nyc.gov), but New York City Police Department has the most data sources associated with it, while all others have 0)
* This may cause issues in other cases where a matched agency may be "close" but not exactly correct

##### Agency divisions with the same homepage url

* Some agencies are split up by precinct and all share the same homepage url
* For example, Baltimore County Police Department [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=baltimorecountymd) all precincts share the same homepage url (baltimorecountymd.gov/police). This means that links such as this: [https://www.baltimorecountymd.gov/departments/police/precinct-news/precinct11/august-10-second-degree-burglary-1500-block-of-hyde-park-road-21221](https://www.baltimorecountymd.gov/departments/police/precinct-news/precinct11/august-10-second-degree-burglary-1500-block-of-hyde-park-road-21221), which is clearly about Precinct 11 specifically, will be matched to the Baltimore County Police Department. Technically correct, but could be more specific

##### Duplicate, incorrect entries

* The database seems to be populated with agencies that share a town name from different states, but the homepage urls for each are the same
* This may cause links to be matched to agencies in incorrect states
* Listed below are a few of the ones I found while working:
    * Knoxville TN, IL [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=knoxvilletn)
    * Harrisburg PA, AR, IL, OH [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=harrisburgpa)
    * East Hampton NY, CT [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=ehamptonny)
    * La Porte TX, IN [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=laportetx)
    * New Castle WA, NE [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=newcastlewa)
    * Greenville SC, IN, ME [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=greenvillesc)
    * Stockton CA, KS [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=stocktonca)
    * Altoona PA, IA [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=altoonapa)
    * Beaver County PA, OK [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=beavercountypa)
* There are also some entries for nearby towns that have separate police departments, but their homepage url are all the same. Such as Mattoon, Shelbyville, and Sullivan, IL [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=mattoon.illinois) are all listed with the homepage mattoon.illinois.gov despite being different towns with their own police departments.

##### Facebook.com

* If we ever supply the identifier with Facebook links, it will likely lead to incorrect matches since a lot of departments' homepage is a Facebook page

##### Chicago.gov

* The only agency registered under www.chicago.gov is the Chicago Department of Aviation Police Department (CDAPD): https://www.chicago.gov/city/en/depts/doa.html [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=chicago)
* Chicago PD has a homepage url of https://home.chicagopolice.org/
* This means this link will match to CDAPD: https://www.chicago.gov/content/city/en/depts/cpb/auto_generated/police_discipline_publandreports.html
* While technically a match to the CDAPD is the correct city and a division of the Chicago PD, the agency described by the link would more closely match Chicago PD

##### Njoag.gov (missing agency)

* The closest possible match for links at www.njoag.gov domain is Division of Alcoholic Beverage Control - NJ at https://www.njoag.gov/about/divisions-and-offices/division-of-alcoholic-beverage-control-home/ [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_homepage_url=njoag.gov)
* www.njoag.gov is the New Jersey Attorney General's office website and could use its own agency row, not all links pertain to Division of Alcoholic Beverage Control, such as https://www.njoag.gov/tag/bayonne-police-department/

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
OK, the mermaid graph??

**Comment by josh-chamberlain** [comment]
1. As a fallback, selecting the "most data sources" is good but too error-prone. It's maybe better to leave those unidentified—especially if we could log which methods we'd tried already.
2. What if we try to pin down URLs geographically first? We should be hitting the page upstream in this process to [collect HTML metadata](https://github.com/Police-Data-Accessibility-Project/data-source-identification/tree/main/html-tag-collector), and we could see if that's reliably included in the footer or something. That gives the script a smaller set of potential agencies to choose from. Then, if we can't ID the agency, we can at least return the source in a geographic search. This would mean storing some geographic data on the data source table, rather than pulling it from agencies.
3. Keeping it county-level instead of worrying about the precincts is fine by me. I would prefer we didn't have precinct level agencies, or split city agencies up across 10 divisions.

**Comment by josh-chamberlain** [comment]
@mbodeantor this is over to you—I'm thinking we might want to have a working session about data source identification—it's a big thing to wade into.

**Comment by EvilDrPurple** [comment]
@josh-chamberlain 

> I would prefer we didn't have precinct level agencies, or split city agencies up across 10 divisions.

Just to be clear on this, I wasn't sure exactly what you meant but the database already has lots of precinct agencies and I was accounting for that. Just to make you aware if you weren't already [Airtable link](https://airtable.com/app473MWXVJVaD7Es/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX?filterContains_name=precinct)

I'll get to work on the other stuff though. Shouldn't be too difficult, though I'm not sure if the html-tag-collector will add a significant amount of execution time or not and may need threading to make it viable for cases with thousands of links

**Comment by EvilDrPurple** [comment]
Okay, I added a status column to the output that either says "Match found", "No match found", or "Contested match". This also means that ~41% of links are successfully identified now. I checked on the tag collector and it doesn't seem to collect footer data at the moment, but could be modified to do so if that's something you believe should be done

**Comment by josh-chamberlain** [comment]
@EvilDrPurple yeah, those are in the db but using the primary agency is preferred. I don't have a strong enough opinion to go and eliminate/merge all those agencies. 

One thing about the tag collector: let's make sure we're only hitting these pages once, and using that HTML response throughout the process as needed. That doesn't have to be part of this issue, but it might mean the tag collector gets cannibalized into a module in the pipeline.

**Comment by mbodeantor** [comment]
If you got it to run in about a minute, I'm not sure further optimization would be worth the effort. However I did notice that the script loops through all agencies for every URL that is checked, with Pandas it would be trivial to merge these two datasets and find all potential matches at once. But again, not sure it's worth doing until we are trying to process way more URLs.

**Comment by mbodeantor** [comment]
> @mbodeantor this is over to you—I'm thinking we might want to have a working session about data source identification—it's a big thing to wade into.

I think I have enough of a sense of this now to talk about it, I'll post in Discord to schedule

**Review by mbodeantor — APPROVED** [review]
To sum up our conversation earlier, sounds like we're all comfortable with this is at for now. I'll add Josh's suggestions to a new ticket for further work on this after all the initial parts of the data source identification pipeline are complete

**Pull request merged**
