### PR TITLE
Identification pipeline

### PR DESCRIPTION
**Pull request by mbodeantor**
docs, minor fixes, cleanup

### CODE REVIEW

**Review by josh-chamberlain — CHANGES_REQUESTED** [review]
Having issues when I try to run this. I made a venv and wrote requirements based on what was missing when I first tried, then made a new venv, installed requirements, and got the following:

```
  warnings.warn(
Traceback (most recent call last):
  File "/Users/joshchamberlain/dev/data-source-identification/identification_pipeline.py", line 30, in <module>
    df = pl.read_csv(sys.argv[1])
  File "/Users/joshchamberlain/dev/data-source-identification/venv/lib/python3.9/site-packages/polars/io/csv/functions.py", line 366, in read_csv
    df = pl.DataFrame._read_csv(
  File "/Users/joshchamberlain/dev/data-source-identification/venv/lib/python3.9/site-packages/polars/dataframe/frame.py", line 775, in _read_csv
    self._df = PyDataFrame.read_csv(
polars.exceptions.ComputeError: found more fields than defined in 'Schema'

Consider setting 'truncate_ragged_lines=True'.
```

**Comment by mbodeantor** [comment]
@josh-chamberlain what's the command you ran/file you used?

**Comment by josh-chamberlain** [comment]
@mbodeantor I forgot to push my commit, I just tweaked a couple things and added an example file.

I made a venv then installed requirements and ran `python3 identification_pipeline.py urls.csv`.

**Comment by mbodeantor** [comment]
@josh-chamberlain ah yeah it requires at least one other column, I'll update the doc

**Comment by josh-chamberlain** [comment]
@mbodeantor I just fixed the example csv, it was formatted incorrectly. getting a different error:

```
(venv) joshchamberlain@MacBook-Pro data-source-identification % python3 identification_pipeline.py urls.csv
/Users/joshchamberlain/dev/data-source-identification/venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/joshchamberlain/dev/data-source-identification/identification_pipeline.py", line 31, in <module>
    identified_df = identification_pipeline_main(df)
  File "/Users/joshchamberlain/dev/data-source-identification/identification_pipeline.py", line 17, in identification_pipeline_main
    api_key = "Bearer " + os.getenv("VUE_APP_PDAP_API_KEY")
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by mbodeantor** [comment]
@josh-chamberlain should be fixed now

**Review by josh-chamberlain — APPROVED** [review]

**Pull request merged**
