### PR TITLE
mc_revise_pr_type_checking_and_linting

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

* Enhances #73 

#### Description

* The prior implementation include a lot of logic within the yaml file itself and was consequently difficult to debug and prone to unexpected errors.
* The new version migrates the majority of logic into python scripts, where the logic is rendered more comprehensible.
* Additionally, substantial logging has been added, to further improve debugging capabilities.

#### Testing

* Internal testing has been added via `test_type_and_docstyle_checking.py`

Prior testing was demonstrated in the following PRs:
* [This PR](https://github.com/maxachis/Github-Action-Test/pull/1#issuecomment-2043748474), which (after a few modifications) showcases how it would work on a PR
* [This other PR](https://github.com/maxachis/Github-Action-Test/pull/2), which shows it functioning again, but now _only on the new file I've created_. The other file, despite not being corrected, is not checked -- it only runs these checks on files that have been modified.

#### Performance

* As before, the Github action is light, and should run in 30 seconds or less
* Some overhead is added by transferring logic to Python, but this performance cost should be in the realm of milliseconds.
* In the case of performance dips, additional enhancements can be done to cache `mypy` and `pydocstyle` modules, although these are fairly light regardless

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
Thanks for making test issues so we can quickly see the behavior!

1. I can't find where I commented this before, but this adds some comment/notifications noise. Is there always going to be a comment, or is there a way for it to show up as a test as in the PR I'm commenting on? Is there a `neutral` option, so it's not a pass/fail test, or a way to label it "optional" or "advisory"? This is the perfect contextual place to deliver that kind of information, and update it when it changes:

Screen Shot 2024-04-19 at 12 04 33 PM


2. From your comment: 
> One challenge here seems to be that my current iteration doesn't play nice with forked branches. I'll see if I can tweak that.

Is that resolved? Anyone not explicitly added as a contributor will be making forks instead of branches.

**Comment by maxachis** [comment]
@josh-chamberlain 
1. Unfortunately, there's no `advisory` option when it comes to Github Actions. However, there are other options. One of them is to post a single comment for the checks, and have any subsequent runs update that same comment. That would in my view be the best way to balance it, but I'll defer to your thoughts on the matter. 
2. Not yet resolved, but currently testing out that now.

**Comment by maxachis** [comment]
@josh-chamberlain After much trial and error, I seem to have found the best solution, one that indeed utilizes `check runs` and is much simpler in execution, to boot. If you look at the "Files Changed" tab, you can see the results. Have a look and give me your thoughts.

One next step might be to decide which annotations we _don't_ want. It's probably easier to suggest modifications to this as we go along and find ones we think are disruptive.

**Comment by josh-chamberlain** [comment]
thanks for being willing to go back to various drawing boards @maxachis ! I think it's much nicer in the `check runs` section, and the inline notes are perfect. As someone who never contributes Python code, I will defer to others on which annotations we care about, but it seems these can all be safely ignored if needed

**Comment by maxachis** [comment]
@mbodeantor What are your thoughts? How does this look, and what annotations might we want to keep?

**Comment by maxachis** [comment]
> @maxachis couldn't we reuse the github actions using black from data-sources-app?

@mbodeantor Black functions as a Code formatter, not a code linter. Thus, while Black is useful for ensuring that code adheres to a specific format, it will not check for docstring formatting, type hinting issues, unused variables, or other problems.

**Comment by mbodeantor** [comment]
Ah nice. Yeah I would say we go with this for now and make changes as seem appropriate moving forward. There's a lot of tickets around the V2 changes so it would be a huge help to get some focus on those

**Review by mbodeantor — APPROVED** [review]

**Pull request merged**
