### PR TITLE
Minor tag collector updates

### PR DESCRIPTION
**Pull request by EvilDrPurple**
#### Description

* A couple features requested by @bonjarlow 
* The tag collector ignores header tags containing links to reduce bias with websites laid out in a similar fashion
* Adds a separate column `url_path` that stores the path of the url to reduce hostname bias

### CODE REVIEW

**Comment by mbodeantor** [comment]
@EvilDrPurple I created a clean virtualenv and install from requirements.txt but am getting an error referencing the requests_html package:
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.

**Comment by EvilDrPurple** [comment]
> @EvilDrPurple I created a clean virtualenv and install from requirements.txt but am getting an error referencing the requests_html package: ImportError: lxml.html.clean module is now a separate project lxml_html_clean. Install lxml[html_clean] or lxml_html_clean directly.

@mbodeantor I updated the requirements.txt file. Seems like a recent lxml update to 5.2.0 broke one of the imports in requests_html. At least for now the version is now capped at 5.1.1 so that everything still works.

**Comment by EvilDrPurple** [comment]
> these changes make sense! could you please leave some comments in-code explaining the logic so we don't forget? even a copy paste from the PR would be fine.

@josh-chamberlain comments added!

**Review by mbodeantor — APPROVED** [review]

**Review by josh-chamberlain — APPROVED** [review]
I didn't realize I was still blocking 👀

**Pull request merged**
