### PR TITLE
Mc common crawl db connection

### LINKED ISSUE #40: feature: add common crawl to the pipeline
This is a simple script which fetches URLs from common crawl. It should accept a `keyword` like "police" or "misconduct" and return a batch of `10,000` URLs. These URLs will then go into the annotation part of the pipeline.

- [ ] create commoncrawler.py (#45)
- [ ] move the URLs to the labeling phase
   - one idea: using the hugging face dataset called `urls-to-label` (see `urls-relevance`)
   - generate a new .csv file for each commoncrawler batch
      - working in batches will help us keep things manageable, close things out (remove old irrelevant data), and test different strategies
   - run the `url-relevance` model on each batch, marking urls as `relevant` and `not relevant`
      - generate an HF pull request

Now, we can use these datasets to generate labeling tasks in Label Studio, only for `relevant` urls

Our scripts for triggering this behavior in various APIs could probably use GitHub Actions

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

#40 - Add Common Crawl to the Pipeline

#### Description

This code enables uploading common crawl results to the [unlabeled-urls dataset in HuggingFace](https://huggingface.co/datasets/PDAP/unlabeled-urls). 

It additionally sets up a Github Action that will perform the above process at 1AM every day and commit the updated cache back to the repository. 

#### Testing

Run the following unit and integration test scripts located in the `tests` directory.
1. `test_common_crawler_integration.py`
2. `test_common_crawler_unit.py`
3. `test_util_unit.py`

Additionally, follow the instructions in `common_crawler/README.md` to manually run the script and confirm functionality. The script, once completed, should yield the following results:
1. If relevant URLs were found, the new relevant URLs will be located in the aforementioned HuggingFace dataset.
2. The cache should be updated now such that, if the same command is run, the crawler will resume at the page after the last page crawled in the previous execution of `main.py`

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
Nice! I would also suggest we name/id batches this way: `YYMMDD-1` and count up from 1. The `name` is the `id
`
We should probably also use this moment to create a log of the batch somewhere—probably a machine readable file in the GitHub repo somewhere. we should track `id` `count` and `keywords` or other common crawl input data. We can add things over time, but just to get it started.

**Comment by mbodeantor** [comment]
@maxachis It's unclear to me where to store the HuggingFace token, can you add that to the README?

**Comment by maxachis** [comment]
> @maxachis It's unclear to me where to store the HuggingFace token, can you add that to the README? Getting this error when I try to run the tests: FAILED test_common_crawler_integration.py::test_main_with_valid_args - ValueError: Access token cannot be empty.

Good catch. I've added additional instructions in the README (and some descriptive error catching in MAIN that provides additional context!

**Review by mbodeantor — APPROVED** [review]
Thanks!

**Pull request merged**
