### PR TITLE
Implement Python type checking and docstring validation checks

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

* [#213](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/213) - This is from data-sources-app, but can be equally applied here.

#### Description

* Implemented docstring checks through pydocstyle and added Python checks in Github Actions. 
* The Python checks include running `mypy` and `pydocstyle` on modified Python files and commenting the output on the associated pull request.
* It is designed to only run on files that have been modified in the pull request.

#### Testing

Testing has already been demonstrated in the following PRs:
* [This PR](https://github.com/maxachis/Github-Action-Test/pull/1#issuecomment-2043748474), which (after a few modifications) showcases how it would work on a PR
* [This other PR](https://github.com/maxachis/Github-Action-Test/pull/2), which shows it functioning again, but now _only on the new file I've created_. The other file, despite not being corrected, is not checked -- it only runs these checks on files that have been modified.

#### Performance

* This Github action is quite light, consistently running in under 30 seconds.

### CODE REVIEW

**Review by josh-chamberlain — COMMENTED** [review]
@maxachis thank you! one thing just occurred to me: what if we made these part of the checks which are pass/fail on PRs? One less comment/notification per PR, seems worth it to me—and I don't believe it prevents you pushing commits/opening PRs

Screen Shot 2024-04-15 at 2 16 45 PM

**Review by josh-chamberlain — APPROVED** [review]

**Comment by maxachis** [comment]
@josh-chamberlain Done. Because I made changes, I won't also perform the merge, so you get to press the fun green button ✅

**Comment by mbodeantor** [comment]
@maxachis looks like there is an error in checks still

**Comment by maxachis** [comment]
> @maxachis looks like there is an error in checks still

@mbodeantor Thanks for the catch. I needed to make sure it checks for errors only if files have been modified. That's been resolved.

**Pull request merged**
