### PR TITLE
Mc common crawl enhancements

### LINKED ISSUE #66: common crawler enhancements
### Context

Follows #52 

Just tying up a couple loose ends we merged before addressing:

### Requirements

- I would also suggest we name/id batches this way: `YYMMDD-1` and count up from 1. The `name` is the same as the `id`. We could also add a code for the source, like `YYMMDD-CC-1` to show it's a common crawl batch, as opposed to future methods of generating batches.
- We should probably also use this moment to create a log of the batch somewhere—probably a machine readable file in the GitHub repo. we should track `id` `count` and `keywords` or other common crawl input data. We can add things over time, but those are to get it started.
- Let's avoid making this run daily. Until we process the first batch, we're not ready for the second. These will pile up + get intimidating, so we can click the action manually for now.

#### batch file example

name | count | keywords
-- | -- | --
240403-CC-1 | 10000 | police,.gov
240403-CC-2 | 10000 | police,.gov

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

#66 - Common Crawler Enhancements 

#### Description

This enhances the `common_crawler` module by adding batch logging. Additionally, it modifies the Github Actions yaml file to only run on manual command, rather than automatically.

#### Testing

Run the following unit and integration test scripts located in the `tests` directory.
1. `test_common_crawler_integration.py`
2. `test_common_crawler_unit.py`
3. `test_util_unit.py`

Additionally, follow the instructions in `common_crawler/README.md` to manually run the script and confirm functionality. The script, once completed, should yield the following results:
1. If relevant URLs were found, the new relevant URLs will be located in the aforementioned HuggingFace dataset.
2. The cache should be updated now such that, if the same command is run, the crawler will resume at the page after the last page crawled in the previous execution of `main.py`
3. The `batch_info.csv` file in the `data` directory of `common_crawler` should provide information about the batch, including the number of urls uploaded, the source, and additional relevant details

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
I think @bonjarlow mentioned wanting to work on https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/68, and will need to test this PR as part of that anyway

**Review by mbodeantor — APPROVED** [review]
LGTM pending Jon's review

**Review by bonjarlow — COMMENTED** [review]
works well!

1. URL's written to unlabeled-urls on HF, pgs 11 - 13 of crawl for police in *.gov
2. reran command and it resumed at pg 13 as expected
3. batch info correct
2024-04-16 00:00:35.715813,Common Crawl,60,*.gov - police,"CC-MAIN-2023-50, 2 pages, starting at 11"
2024-04-16 00:33:38.052802,Common Crawl,37,*.gov - police,"CC-MAIN-2023-50, 2 pages, starting at 13"

I can add in the readme:

1. requires python >= 3.10
2. to run unit/integration test scripts had to add data_source_identification/ in python path (and run tests from parent directory)
3. in zsh shell a wildcard argument (eg *.gov) will be misinterpreted if not in quotes ('*.gov')

**Review by josh-chamberlain — CHANGES_REQUESTED** [review]
Let's just resolve the @bonjarlow comment before merging, but looks good

**Review by josh-chamberlain — APPROVED** [review]

**Comment by josh-chamberlain** [comment]
great, thank you @maxachis !

**Pull request merged**
